# -*- coding: utf-8 -*-
"""Aula_10-Tarefa_2_Filtro_Elíptico_Passa-Banda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ywy5iWo7_7HFMhQsSqy6dUFA-9ZR-FN-
"""

from scipy import signal
import matplotlib.pyplot as plt
import matplotlib.ticker
import numpy as np

fs = 10000
wp = [3000/fs, 6000/fs]
ws = [1000/fs, 8000/fs]
gpass = 1
gstop = 20

b, a = signal.iirdesign(wp, ws, gpass, gstop, analog=False, ftype='ellip')
w, h = signal.freqz(b,a)

fig, ax1 = plt.subplots()
ax1.set_title('Resposta em Frequencia do Filtro Digital Elíptico Pass-Band')
ax1.plot(w*20/(np.pi), abs(h), 'b')
ax1.set_ylabel('Magnitude', color='b')
ax1.set_xlabel('Frequência [kHz]')
ax1.grid()
ax1.set_ylim([0, 1.01])
ax1.set_xlim([0, 20])
nticks = 8
ax1.yaxis.set_major_locator(matplotlib.ticker.LinearLocator(nticks))
fig.show()

b

a